using static Solamnia;
using Microsoft.AspNetCore.Builder;
using ProjectSolamnia.Server;
using ProjectSolamnia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;

// See https://aka.ms/new-console-template for more information

var exampleCharacter = new Character(
    id: 0,  // Will be auto-generated by database
    name: "Eddard Stark",
    age: 35,
    rank: "Lord of Winterfell",
    status: StatusType.AD,
    assignedHoldingId: null,  // No holding assigned
    assignedHolding: null,    // No holding object
    activeDuty: "On Campaign",
    diplomacy: 14,
    martial: 16,
    stewardship: 12,
    intrigue: 10,
    learning: 13,
    prowess: 15,
    traits: null  // No traits assigned
);

var optionsBuilder = new DbContextOptionsBuilder<ProjectSolamniaDbContext>();
optionsBuilder.UseSqlite("Data Source=data/projectsolamnia.db");
ProjectSolamniaDbContext db = new ProjectSolamniaDbContext(optionsBuilder.Options);

db.addCharacter(exampleCharacter);
Console.WriteLine("Added character.");