// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectSolamnia;

#nullable disable

namespace ProjectSolamnia.Migrations
{
    [DbContext(typeof(ProjectSolamniaDbContext))]
    [Migration("20250617041404_traits")]
    partial class traits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("ProjectSolamnia.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activeduty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedHoldingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Diplomacy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intigue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Learning")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Martial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Prowess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stewardship")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedHoldingId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("ProjectSolamnia.CharacterTrait", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TraitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "TraitId");

                    b.HasIndex("TraitId");

                    b.ToTable("CharacterTraits");
                });

            modelBuilder.Entity("ProjectSolamnia.Holding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Holding");
                });

            modelBuilder.Entity("ProjectSolamnia.Trait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Traits");
                });

            modelBuilder.Entity("ProjectSolamnia.TraitExclusive", b =>
                {
                    b.Property<int>("TraitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExclusiveWithTraitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TraitId", "ExclusiveWithTraitId");

                    b.HasIndex("ExclusiveWithTraitId");

                    b.ToTable("TraitExclusives");
                });

            modelBuilder.Entity("ProjectSolamnia.Character", b =>
                {
                    b.HasOne("ProjectSolamnia.Holding", "AssignedHolding")
                        .WithMany()
                        .HasForeignKey("AssignedHoldingId");

                    b.Navigation("AssignedHolding");
                });

            modelBuilder.Entity("ProjectSolamnia.CharacterTrait", b =>
                {
                    b.HasOne("ProjectSolamnia.Character", "Character")
                        .WithMany("CharacterTraits")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectSolamnia.Trait", "Trait")
                        .WithMany("CharacterTraits")
                        .HasForeignKey("TraitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Trait");
                });

            modelBuilder.Entity("ProjectSolamnia.TraitExclusive", b =>
                {
                    b.HasOne("ProjectSolamnia.Trait", "ExclusiveWithTrait")
                        .WithMany()
                        .HasForeignKey("ExclusiveWithTraitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectSolamnia.Trait", "Trait")
                        .WithMany("ExclusiveWithTraits")
                        .HasForeignKey("TraitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExclusiveWithTrait");

                    b.Navigation("Trait");
                });

            modelBuilder.Entity("ProjectSolamnia.Character", b =>
                {
                    b.Navigation("CharacterTraits");
                });

            modelBuilder.Entity("ProjectSolamnia.Trait", b =>
                {
                    b.Navigation("CharacterTraits");

                    b.Navigation("ExclusiveWithTraits");
                });
#pragma warning restore 612, 618
        }
    }
}
