// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectSolamnia;

#nullable disable

namespace ProjectSolamnia.Migrations
{
    [DbContext(typeof(ProjectSolamniaDbContext))]
    [Migration("20250621023603_console")]
    partial class console
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("ProjectSolamnia.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activeduty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedHoldingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Diplomacy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intrigue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Learning")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Martial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Prowess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stewardship")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedHoldingId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("ProjectSolamnia.CharacterTrait", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TraitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "TraitId");

                    b.HasIndex("TraitId");

                    b.ToTable("CharacterTraits");
                });

            modelBuilder.Entity("ProjectSolamnia.Holding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TroopsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Holdings");
                });

            modelBuilder.Entity("ProjectSolamnia.Trait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusDiplomacy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusIntrigue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusLearning")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusMartial")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusProwess")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusStewardship")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Traits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BonusDiplomacy = 1,
                            BonusIntrigue = 1,
                            BonusLearning = 1,
                            BonusMartial = 1,
                            BonusProwess = 1,
                            BonusStewardship = 1,
                            Description = "This character burns with a relentless drive to rise above all others. They crave greatness and will stop at nothing to carve their name into history—even if it means stepping on friends, family, or tradition.",
                            Name = "Ambitious",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 3,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Justice and reason are strangers to this character. Their whims govern their rule, their moods define their verdicts. To serve them is to live in constant uncertainty.",
                            Name = "Arbitrary",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            BonusDiplomacy = 1,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Convinced of their own superiority, this character dismisses the opinions of others with a smirk. Humility is a word they’ve heard but never needed.",
                            Name = "Arrogant",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 2,
                            BonusProwess = 3,
                            BonusStewardship = 0,
                            Description = "Fear holds no sway over this character. They stand tall in the face of danger, charging into the fray with sword in hand and heart unyielding—even if wisdom says otherwise.",
                            Name = "Brave",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 2,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Empathy is weakness in this character’s eyes. They view pain and loss as tools, not tragedies, and rarely pause to consider the emotional toll of their actions.",
                            Name = "Callous",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            BonusDiplomacy = 1,
                            BonusIntrigue = 1,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Unshaken by chaos and unbothered by insult, this character is a pillar of serenity. Whether in war or council, their steady hand guides with grace.",
                            Name = "Calm",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 2,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "This character resists earthly pleasures, placing purity and discipline above passion. Their restraint is both a virtue and, at times, a wedge between them and others.",
                            Name = "Chaste",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            BonusDiplomacy = 2,
                            BonusIntrigue = -2,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "A heart that aches for the suffering of others beats within this character. Their kindness may inspire loyalty, but it also exposes them to exploitation and sorrow.",
                            Name = "Compassionate",
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            BonusDiplomacy = 0,
                            BonusIntrigue = -1,
                            BonusLearning = 2,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "This character desires little beyond what they already possess. Their peaceful nature brings them happiness—but ambitionless calm can be a dangerous flaw in a turbulent world.",
                            Name = "Content",
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 2,
                            BonusLearning = 0,
                            BonusMartial = -2,
                            BonusProwess = -3,
                            BonusStewardship = 0,
                            Description = "Self-preservation guides every step of this character. They shrink from conflict and avoid risk, preferring to survive in the shadows rather than die in the light.",
                            Name = "Craven",
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 4,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "This character weaves lies like a spider spins webs. Deception is their tool, and truth is a burden they rarely carry. To trust them is to invite betrayal.",
                            Name = "Deceitful",
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            BonusDiplomacy = 1,
                            BonusIntrigue = 1,
                            BonusLearning = 1,
                            BonusMartial = 1,
                            BonusProwess = 1,
                            BonusStewardship = 1,
                            Description = "Industrious and relentless, this character pours their soul into every task. Their work ethic inspires others, but it can also lead them to exhaustion.",
                            Name = "Diligent",
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Unbound by norms, this character marches to a beat only they can hear. Their odd behavior confounds others, sometimes charming, often confusing.",
                            Name = "Eccentric",
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            BonusDiplomacy = 1,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Inconstant and changeable, this character’s loyalties and moods shift like the wind. Their unpredictability makes alliances both risky and fleeting.",
                            Name = "Fickle",
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            BonusDiplomacy = 2,
                            BonusIntrigue = -2,
                            BonusLearning = 1,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "This character’s heart is quick to pardon, even when justice might demand otherwise. Their mercy heals wounds, but it can also enable wrongdoing.",
                            Name = "Forgiving",
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            BonusDiplomacy = 3,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Gold flows from this character’s hands like water. Whether out of kindness or a desire to be loved, they give freely, sometimes to their own detriment.",
                            Name = "Generous",
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Pleasure and indulgence are this character’s constant companions. They feast, drink, and consume without thought for moderation or judgment.",
                            Name = "Gluttonous",
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "This character hungers for wealth above all else. Coins are their closest companions, and they are rarely seen giving without expecting more in return.",
                            Name = "Greedy",
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            BonusDiplomacy = 2,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Charming and outgoing, this character thrives in the company of others. Their laughter is infectious, their presence magnetic.",
                            Name = "Gregarious",
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            BonusDiplomacy = 2,
                            BonusIntrigue = -4,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "This character values truth as a sacred duty. Their candor is refreshing to some and dangerous to others, especially in a world ruled by secrets.",
                            Name = "Honest",
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "This character carries little pride, preferring to downplay their own achievements. Their humility is admirable—but it can be mistaken for weakness.",
                            Name = "Humble",
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "This character has little tolerance for delay or indecision. They act quickly—sometimes recklessly—and despise idle waiting or long debates.",
                            Name = "Impatient",
                            Type = 0
                        },
                        new
                        {
                            Id = 23,
                            BonusDiplomacy = 0,
                            BonusIntrigue = -3,
                            BonusLearning = 1,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 2,
                            Description = "Guided by law and fairness, this character strives to do what is right—even when the cost is high. Justice is their compass, and compromise is not in their nature.",
                            Name = "Just",
                            Type = 0
                        },
                        new
                        {
                            Id = 24,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 2,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Driven by carnal desires, this character embraces passion without restraint. Whether through charm or indulgence, they rarely deny themselves pleasure.",
                            Name = "Lustful",
                            Type = 0
                        },
                        new
                        {
                            Id = 25,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "This character avoids effort whenever possible, preferring rest over toil. Duties are often neglected in favor of comfort and ease.",
                            Name = "Lazy",
                            Type = 0
                        },
                        new
                        {
                            Id = 26,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 2,
                            BonusLearning = 0,
                            BonusMartial = 3,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Suspicious of all, this character sees plots and betrayal around every corner. Trust is a foreign concept—and fear is their only constant ally.",
                            Name = "Paranoid",
                            Type = 0
                        },
                        new
                        {
                            Id = 27,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 2,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Slow to anger and deliberate in action, this character believes that good things come to those who wait—and they are always willing to wait.",
                            Name = "Patient",
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 2,
                            BonusLearning = 0,
                            BonusMartial = 2,
                            BonusProwess = 1,
                            BonusStewardship = 0,
                            Description = "This character finds satisfaction in the suffering of others. Whether through cruelty or vengeance, they revel in power over pain.",
                            Name = "Sadistic",
                            Type = 0
                        },
                        new
                        {
                            Id = 29,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Quiet and reserved, this character avoids the spotlight. Crowds are discomforting, and small talk is a source of anxiety.",
                            Name = "Shy",
                            Type = 0
                        },
                        new
                        {
                            Id = 30,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 3,
                            Description = "Once this character has made up their mind, it is nearly impossible to sway them. Their resolve is ironclad, for better or worse.",
                            Name = "Stubborn",
                            Type = 0
                        },
                        new
                        {
                            Id = 31,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 2,
                            Description = "Moderation defines this character’s habits. They avoid indulgence and temptation, living a life of balance and restraint.",
                            Name = "Temperate",
                            Type = 0
                        },
                        new
                        {
                            Id = 32,
                            BonusDiplomacy = 2,
                            BonusIntrigue = -2,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Naive or idealistic, this character gives others the benefit of the doubt. Unfortunately, this often leads them into dangerous traps.",
                            Name = "Trusting",
                            Type = 0
                        },
                        new
                        {
                            Id = 33,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 2,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "This character never forgets a slight. Grudges are cherished like treasures, and revenge is a promise they always intend to keep.",
                            Name = "Vengeful",
                            Type = 0
                        },
                        new
                        {
                            Id = 34,
                            BonusDiplomacy = -1,
                            BonusIntrigue = -1,
                            BonusLearning = 0,
                            BonusMartial = 2,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Quick-tempered and easily provoked, this character is a storm waiting to explode. Their fury inspires fear—and often regret.",
                            Name = "Wrathful",
                            Type = 0
                        },
                        new
                        {
                            Id = 35,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 2,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Fanatical in their beliefs, this character serves a higher power with unwavering devotion. To them, heresy is not a difference of opinion—it's a crime.",
                            Name = "Zealous",
                            Type = 0
                        },
                        new
                        {
                            Id = 36,
                            BonusDiplomacy = 2,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Though trained in diplomacy, this character’s clumsy attempts at negotiation often result in embarrassment. Their intentions are good, but the execution falls painfully short.",
                            Name = "Naive Appeaser",
                            Type = 1
                        },
                        new
                        {
                            Id = 37,
                            BonusDiplomacy = 4,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "This character has found some success in the diplomatic arena, though it’s unclear whether it’s through talent or sheer luck. Still, they hold their own in courtly matters.",
                            Name = "Adequate Bargainer",
                            Type = 1
                        },
                        new
                        {
                            Id = 38,
                            BonusDiplomacy = 6,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Gifted with silvered words and natural charm, this character navigates diplomacy with confidence. Courtiers hang on their every word, and few can deny their appeals.",
                            Name = "Charismatic Negotiator",
                            Type = 1
                        },
                        new
                        {
                            Id = 39,
                            BonusDiplomacy = 8,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "This master of diplomacy commands influence behind the scenes with unmatched skill. Subtle and refined, they bend even the most stubborn wills without lifting a sword.",
                            Name = "Grey Eminence",
                            Type = 1
                        },
                        new
                        {
                            Id = 40,
                            BonusDiplomacy = 10,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 3,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "With eloquence honed to a fine edge, this character can untangle the most volatile disputes and charm the bitterest rivals. Diplomacy isn’t just a skill—it’s their art.",
                            Name = "Virtuoso Arbitrator",
                            Type = 1
                        },
                        new
                        {
                            Id = 41,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 2,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Armed with theory but lacking in practice, this character's martial education is more of a liability than an asset. They often do more harm to themselves than their foes.",
                            Name = "Misguided Warrior",
                            Type = 1
                        },
                        new
                        {
                            Id = 42,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 4,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "This character has a working grasp of martial matters and some experience in the field, though they still have much to learn before mastering the art of war.",
                            Name = "Tough Soldier",
                            Type = 1
                        },
                        new
                        {
                            Id = 43,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 6,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "A proven battlefield leader, this character commands with confidence and knows how to turn the tide of war through calculated tactics.",
                            Name = "Skilled Tactician",
                            Type = 1
                        },
                        new
                        {
                            Id = 44,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 8,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "War is a game, and this character is a grandmaster. No martial detail escapes their attention, and every campaign is a well-orchestrated symphony of steel.",
                            Name = "Brilliant Strategist",
                            Type = 1
                        },
                        new
                        {
                            Id = 45,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 10,
                            BonusProwess = 0,
                            BonusStewardship = 3,
                            Description = "Renowned across kingdoms, this character leads armies with unmatched brilliance. Their feats in battle are the stuff of legend, and entire wars bend to their will.",
                            Name = "Exalted Warlord",
                            Type = 1
                        },
                        new
                        {
                            Id = 46,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 2,
                            Description = "Educated in stewardship but devoid of restraint, this character is more likely to spend wealth than manage it. Prosperity slips through their fingers like sand.",
                            Name = "Indulgent Wastrel",
                            Type = 1
                        },
                        new
                        {
                            Id = 47,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 4,
                            Description = "Competent and careful, this character can manage a budget and oversee estates, even if their talents occasionally fall short.",
                            Name = "Thrifty Clerk",
                            Type = 1
                        },
                        new
                        {
                            Id = 48,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 6,
                            Description = "Savvy and detail-oriented, this character excels in managing lands and treasuries, turning modest ventures into wealth-generating enterprises.",
                            Name = "Fortune Builder",
                            Type = 1
                        },
                        new
                        {
                            Id = 49,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 8,
                            Description = "Everything this character touches turns to gold. A paragon of stewardship, they manage resources with unrivaled efficiency and vision.",
                            Name = "Midas Touched",
                            Type = 1
                        },
                        new
                        {
                            Id = 50,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 3,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 10,
                            Description = "An economic mastermind, this character elevates even failing realms into beacons of prosperity. Their brilliance shines brightest in coin and crown.",
                            Name = "Golden Sovereign",
                            Type = 1
                        },
                        new
                        {
                            Id = 51,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 2,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "While trained in subterfuge, this character often blunders their schemes. Their plots are usually transparent and ineffective, but at least they try.",
                            Name = "Amateurish Plotter",
                            Type = 1
                        },
                        new
                        {
                            Id = 52,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 4,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Dramatic and cunning, this character knows their way around intrigue but often takes flashy risks that may backfire.",
                            Name = "Flamboyant Trickster",
                            Type = 1
                        },
                        new
                        {
                            Id = 53,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 6,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "This character has a mind for manipulation and secrets, spinning lies as easily as others breathe. Their reach is long and subtle.",
                            Name = "Intricate Webweaver",
                            Type = 1
                        },
                        new
                        {
                            Id = 54,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 8,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Few have seen their true face. This master of secrecy and deception leaves little trace, ruling through whispers and threats.",
                            Name = "Elusive Shadow",
                            Type = 1
                        },
                        new
                        {
                            Id = 55,
                            BonusDiplomacy = 3,
                            BonusIntrigue = 10,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Every move this character makes pulls on a hidden string. Their mastery of intrigue rivals kings—rulers may sit on the throne, but this one pulls the strings.",
                            Name = "Conniving Puppetmaster",
                            Type = 1
                        },
                        new
                        {
                            Id = 56,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 2,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Their grasp of letters is solid, but beyond that lies confusion. This character has studied learning, yet true insight continues to elude them.",
                            Name = "Conscientious Scribe",
                            Type = 1
                        },
                        new
                        {
                            Id = 57,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 4,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "This character has cultivated a respectable understanding of faith, reason, and the written word. They are a thoughtful student of the world’s mysteries.",
                            Name = "Insightful Thinker",
                            Type = 1
                        },
                        new
                        {
                            Id = 58,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 6,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Possessing both curiosity and discipline, this character dives deep into philosophical and theological debates, often leading scholars in discussion.",
                            Name = "Astute Intellectual",
                            Type = 1
                        },
                        new
                        {
                            Id = 59,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 8,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "This brilliant mind sees connections others miss. Their insights shape doctrine and reform, often setting the course of intellectual history.",
                            Name = "Mastermind Philosopher",
                            Type = 1
                        },
                        new
                        {
                            Id = 60,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 3,
                            BonusLearning = 10,
                            BonusMartial = 0,
                            BonusProwess = 0,
                            BonusStewardship = 0,
                            Description = "Revered in scholarly and spiritual circles alike, this character’s wisdom guides kings and clergy. They are a living library of divine and secular knowledge.",
                            Name = "Erudite Oracle",
                            Type = 1
                        },
                        new
                        {
                            Id = 61,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 1,
                            BonusStewardship = 0,
                            Description = "Though technically trained, this character struggles with the basics of combat. Their clumsy swordplay is more likely to amuse than intimidate.",
                            Name = "Bumbling Squire",
                            Type = 1
                        },
                        new
                        {
                            Id = 62,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 2,
                            BonusStewardship = 0,
                            Description = "Having earned their spurs, this character is a competent warrior who knows their way around a battlefield and commands respect in melee.",
                            Name = "Confident Knight",
                            Type = 1
                        },
                        new
                        {
                            Id = 63,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 3,
                            BonusStewardship = 0,
                            Description = "Tested in raids and skirmishes, this character leads with grit and strikes with power. Their presence inspires their comrades to press on.",
                            Name = "Formidable Banneret",
                            Type = 1
                        },
                        new
                        {
                            Id = 64,
                            BonusDiplomacy = 0,
                            BonusIntrigue = 0,
                            BonusLearning = 0,
                            BonusMartial = 0,
                            BonusProwess = 4,
                            BonusStewardship = 0,
                            Description = "A legend among warriors, this character’s name echoes across arenas and battlefields. Tales of their feats inspire awe—and fear.",
                            Name = "Famous Champion",
                            Type = 1
                        });
                });

            modelBuilder.Entity("ProjectSolamnia.TraitExclusive", b =>
                {
                    b.Property<int>("TraitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExclusiveWithTraitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TraitId", "ExclusiveWithTraitId");

                    b.HasIndex("ExclusiveWithTraitId");

                    b.ToTable("TraitExclusives");
                });

            modelBuilder.Entity("ProjectSolamnia.Character", b =>
                {
                    b.HasOne("ProjectSolamnia.Holding", "AssignedHolding")
                        .WithMany("AssignedCharacters")
                        .HasForeignKey("AssignedHoldingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedHolding");
                });

            modelBuilder.Entity("ProjectSolamnia.CharacterTrait", b =>
                {
                    b.HasOne("ProjectSolamnia.Character", "Character")
                        .WithMany("CharacterTraits")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectSolamnia.Trait", "Trait")
                        .WithMany("CharacterTraits")
                        .HasForeignKey("TraitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Trait");
                });

            modelBuilder.Entity("ProjectSolamnia.TraitExclusive", b =>
                {
                    b.HasOne("ProjectSolamnia.Trait", "ExclusiveWithTrait")
                        .WithMany()
                        .HasForeignKey("ExclusiveWithTraitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectSolamnia.Trait", "Trait")
                        .WithMany("ExclusiveWithTraits")
                        .HasForeignKey("TraitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExclusiveWithTrait");

                    b.Navigation("Trait");
                });

            modelBuilder.Entity("ProjectSolamnia.Character", b =>
                {
                    b.Navigation("CharacterTraits");
                });

            modelBuilder.Entity("ProjectSolamnia.Holding", b =>
                {
                    b.Navigation("AssignedCharacters");
                });

            modelBuilder.Entity("ProjectSolamnia.Trait", b =>
                {
                    b.Navigation("CharacterTraits");

                    b.Navigation("ExclusiveWithTraits");
                });
#pragma warning restore 612, 618
        }
    }
}
